# Generated by Django 5.0.3 on 2024-03-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_survey_remove_response_questionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('likert', 'Likert Scale')], default='text', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
