# Generated by Django 5.0.3 on 2024-03-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_questionnaireform'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireform',
            name='activity_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireform',
            name='bureau_service_region_acronym',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireform',
            name='team_acronym',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
