# Generated by Django 5.0.3 on 2024-03-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_delete_questionnaireform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='expectation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='quality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='statement1_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='statement2_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='statement3_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='statement4_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='statement5_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='statement6_rating',
            field=models.IntegerField(null=True),
        ),
    ]
