# Generated by Django 5.0.3 on 2024-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_userresponse_activity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='statement_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='sex',
            field=models.BooleanField(null=True),
        ),
    ]
