# Generated by Django 5.0.3 on 2024-03-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_userresponse_doh_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='statement_ratings',
        ),
    ]
