# Generated by Django 5.0.3 on 2024-03-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_remove_userresponse_statement_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
    ]
