# Generated by Django 4.2.11 on 2024-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_remove_choice_question_remove_question_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='team_acronym',
            field=models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], default='choice1', max_length=100),
        ),
    ]
