# Generated by Django 4.2.11 on 2024-04-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_teamacronym_remove_userresponse_team_acronym'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamAcronym',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='team_acronym',
            field=models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], default='choice1', max_length=100),
        ),
    ]
