# Generated by Django 4.2.11 on 2024-04-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_delete_teamacronym_userresponse_team_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='bureau_service_region_acronym',
            field=models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], default='choice1', max_length=100),
        ),
    ]
