# Generated by Django 4.2.11 on 2024-04-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_alter_userresponse_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='activity_name',
            field=models.CharField(choices=[('Accreditation', 'S1'), ('Authentication', 'S2'), ('Certification', 'S3'), ('Data Request', 'S4'), ('Financial Assistance', 'S5'), ('Follow-up', 'S6'), ('Interview/Research', 'S7'), ('Legal Assitance', 'S8'), ('Licensing', 'S9'), ('Medical Assistance', 'S10'), ('Meetings', 'S11'), ('Policy Review', 'S12'), ('Registration', 'S13'), ('Secretariat', 'S14'), ('Submission', 'S15'), ('Technical Assistance', 'S16'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='bureau_service_region_acronym',
            field=models.CharField(choices=[('Administration and Financial Management Team', (('Administrative Service', 'AS'), ('Personnel Administrative Division', 'PAD'), ('Malasakit Program Office', 'MPO'), ('Financial Management Service', 'FMS'))), ('Field Implementation and Coordination Team', (('Center for Health Development I', 'CHD I'), ('Center for Health Development II', 'CHD II'), ('Center for Health Development III', 'CHD III'), ('Center for Health Development IV-A', 'CHD IV-A'), ('Center for Health Development IV-B', 'CHD IV-B'), ('Center for Health Development V', 'CHD V'), ('Center for Health Development VI', 'CHD VI'), ('Center for Health Development VII', 'CHD VII'), ('Center for Health Development VIII', 'CHD VIII'), ('Center for Health Development IX', 'CHD IX'), ('Center for Health Development X', 'CHD X'), ('Center for Health Development XI', 'CHD XI'), ('Center for Health Development XII', 'CHD XII'), ('Center for Health Development NCR', 'CHD NCR'), ('Center for Health Development CAR', 'CHD CAR'), ('Center for Health Development CARAGA', 'CHD CARAGA'), ('Center for Health Development ARMM', 'CHD ARMM'))), ('Health Facilities and Infrastructure Development Team', (('Health Facilities Development Bureau', 'HFDB'), ('Knowledge Management and Information Technology', 'KMITS'))), ('Procurement and Supply Chain Management Team', (('Procurement Service', 'PS'), ('Supply Chain Management Office', 'SCMO'))), ('Health Policy and Systems Development Team', (('Bureau of International Health Cooperation', 'BIHC'), ('Bureau of Local Health Systems and Development', 'BLHSD'), ('Health Human Resource Development Bureau', 'HHRDB'), ('Health Policy Development and Planning Bureau', 'HPDPB'))), ('Health Regulation Team', (('Bureau of Quarantine', 'BOQ'), ('Food and Drug Administration', 'FDA'), ('Health Facilities Services and Regulatory Bureau', 'HFSRB'))), ('Public Health Service Team', (('Disease Prevention and Control Bureau', 'DPCB'), ('Epidemiology Bureau', 'EB'), ('Health Emergency Management Bureau', 'HEMB'), ('Health Promotion and Communication Services', 'HPCS')))], max_length=100),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='team_acronym',
            field=models.CharField(choices=[('Office of the Chief of Staff', 'OCS'), ('Administration and Finance Management Team', 'AFMT'), ('Field Implementation and Coordination Team', 'FICT'), ('Health Facilities and Infrastructure Development Team', 'HFIDT'), ('Public Health Services Team', 'PHST'), ('Health Policy and Systems Development Team', 'HPSDT'), ('Health Regulation Team', 'HRT'), ('Procurement and Supply', 'PSCMT')], max_length=100),
        ),
    ]
