# Generated by Django 4.2.11 on 2024-04-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_userresponse_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
