# Generated by Django 4.2.11 on 2024-04-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_alter_userresponse_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='code',
        ),
    ]
